### ISSUE TITLE
Can you specify what Android API you tested?

### ISSUE THREAD

**Issue by hatem-u** [mbruel/sendSMS#1]
I have tried it on amdroid api 25 and it keeps crashing.

**Comment by mbruel** [comment]
Hi,
I'm a newbie on both Android and Qt for Android.
I've just installed Qt v14.1 with the Android package.
I've downloaded android-ndk-r21.
Then as you can see in the AndroidManifest.xml, my target sdk is API28: Android 9.
I'm releasing on a Xiaomi Redmi Note 5.

What is your crash? Are you deploying in Debug mode?
There are nearly no chances I'll be able to help, but please be more explicit about the crash, maybe someone will be able to help, maybe me...

**Comment by hatem-u** [comment]
I'm on Qt 5.12.7 with Android NDK 21 and I'm deploying to a Samsung J5 running Android 7.1 in debug mode which is the problem because Android N is API 25 lol it's my bad, I didn't look at the manifest file for the minimum API.

I'm also a beginner so we're in the same boat here haha. Thank you for your response, though, I appreciate it.

**Comment by mbruel** [comment]
so you're getting it working?
happy it can help, I shared it for that as it took me several hours of research and fight with Android to get this simple example working...
I've made a "bigger" project using that, I'll probably publish it next week. It's a daemon app polling websites to get SMS to send in a JSON format (REST APIs). That was basically what I wanted to achieve in order to offer free SMS delivery to my future projects ;)

**Comment by hatem-u** [comment]
That sounds fun and I think it's useful and will cost much less than what services like Twilio do because there's no commission in the middle. 

I'm doing something similar: I'm setting up a phone as a server that will be used to receive data (kind of like a REST API) automatically send SMS messages (receipts, payslip, notes, etc.) to clients from the PC but it will only be on LAN because server maintenance costs too much. I took a look at Twilio but it is based in America and the cost per international SMS message is too high.

**Comment by mbruel** [comment]
Well personally the main idea is to have a free service but also to not expose your SMS messages to an external company. [SMS Gateway](https://smsgateway.me/) offers a free service but you don't know what they do with your data...
Can you close the issue if you managed to run it? did you?

**Comment by hatem-u** [comment]
Yes I did, thank you! 😊 

EDIT: Thanks for suggesting me SMS Gateway it looks really promising. I'll dig further into it and I'll see if it meets my requirements.

**Comment by mbruel** [comment]
you're welcome :)

**Comment by mbruel** [comment]
@HatEmU in case you're interested, I've published my main project using this one: [SmsJsonPolling](https://github.com/mbruel/SmsJsonPolling).
It's similar I guess than what can offer SMS gateway but you use your own phones and poll the SMS from any Servers :)

**Comment by hatem-u** [comment]
@mbruel That's similar to my idea. You can add a server that runs within the app using 
[QtWebApp](http://stefanfrings.de/qtwebapp/index-en.html). With that you can make an API similar to [playSMS](https://playsms.org/) where you pass the phone number and message content through the URL as request parameters.
